name: Fossid Stateless Diff Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to scan'
        required: true
        type: number

permissions:
  contents: read
  pull-requests: read

jobs:
  run-diffscan:
    name: Fossid Annotate PR
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    container:
      image: quay.io/fossid/fossid-toolbox:1.5.29
      credentials:
        username: ${{ secrets.FOSSID_CONTAINER_USERNAME }}
        password: ${{ secrets.FOSSID_CONTAINER_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && format('refs/pull/{0}/merge', github.event.inputs.pr_number) || '' }}

      - name: Checkout ignore projects file
        uses: actions/checkout@v4
        with:
          repository: rdkcentral/build_tools_workflows
          sparse-checkout: |
            ignore_projects_fossid
          ref: develop
          path: tools

      - name: Run fossid-toolbox
        env:
          FOSSID_HOST_USERNAME: ${{ secrets.FOSSID_HOST_USERNAME }}
          FOSSID_HOST_TOKEN: ${{ secrets.FOSSID_HOST_TOKEN }}
        run: |
          fossid \
            diffscan \
            --fossid-host $FOSSID_HOST_USERNAME \
            --fossid-token $FOSSID_HOST_TOKEN \
            --format github \
            --fail \
            --ignore-projects tools/ignore_projects_fossid
